image: repo.adeo.no:5443/soknad/soknad-kontantstotte
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: soknad-kontantstotte/internal/isAlive
  readiness:
    path: soknad-kontantstotte/internal/isAlive
prometheus:
  enabled: true
  path: soknad-kontantstotte/internal/metrics
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  - alias: loginservice
    resourceType: restservice