image: repo.adeo.no:5443/soknad/soknad-kontantstotte
team: team-soknad
replicas:
  min: 2
  max: 4
  cpuThresholdPercentage: 50
port: 8080
healthcheck:
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isAlive
prometheus:
  enabled: true
  path: internal/metrics
ingress:
  enabled: true
resources:
  limits:
    cpu: 3
    memory: 786Mi
  requests:
    memory: 512Mi
fasitResources:
  used:
  - alias: appres.cms
    resourceType: baseUrl
  - alias: loginservice
    resourceType: restservice
  - alias: appdynamics
    resourceType: applicationproperties
  - alias: unleash-api
    resourceType: restservice