version: '3'

services:
  visual-test-server:
    image: navikt/node-express:1.0.0
    volumes:
      - ../dev-server:/var/server/
      - ../dist:/var/dist
    ports:
      - 8000:8000
    entrypoint:
      - node
      - /var/server/ci-server.js
  gemini:
    image: repo.adeo.no:5443/soknad/soknad-docker-gemini:1.0.0
    links:
      - visual-test-server
      - chrome
      - hub
    volumes:
      - ./gemini:/var/gemini
      - ./reports/:/reports/
  pa11y:
    image: repo.adeo.no:5443/soknad/soknad-docker-pa11y:1.0.0
    links:
      - visual-test-server
    volumes:
      - ./pa11y/:/var/pa11y/
      - ./reports/:/reports/
    cap_add:
      - SYS_ADMIN
  hub:
    image: selenium/hub
    ports:
      - 4444:4444
  chrome:
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=hub
      - HUB_PORT_4444_TCP_PORT=4444
    ports:
      - 5900
    links:
      - hub