version: '3'

services:
  ci-test-server:
    image: navikt/node-express:1.0.0
    volumes:
      - ../dev-server:/var/server/
      - ../dist:/var/dist
    ports:
      - 8000
    entrypoint:
      - node
      - /var/server/ci-server.js
  jest-image-snapshot:
    image: navikt/docker-jest-image-snapshot:1.0.0
    depends_on:
      - ci-test-server
    volumes:
      - ./jest-image-snapshot/tests:/app/tests
      - ./jest-image-snapshot/baseline:/app/baseline
      - ./reports:/app/reports
  pa11y:
    image: repo.adeo.no:5443/soknad/soknad-docker-pa11y:1.0.0
    depends_on:
      - ci-test-server
    volumes:
      - ./pa11y/:/var/pa11y/
      - ./reports/:/reports/
    cap_add:
      - SYS_ADMIN
  testcafe:
    image: testcafe/testcafe
    command: ["firefox", "/tests/*.ts"]
    depends_on:
      - ci-test-server
    volumes:
      - ./testcafe/:/tests