version: '3'

services:
  ci-test-server:
    image: navikt/node-express:1.0.0
    volumes:
      - ../dev-server:/var/server/
      - ../dist:/var/dist
    ports:
      - 8000:8000
    entrypoint:
      - node
      - /var/server/ci-server.js
  gemini:
    image: repo.adeo.no:5443/soknad/soknad-docker-gemini:1.0.0
    depends_on:
      - ci-test-server
      - chrome
    volumes:
      - ./gemini:/var/gemini
      - ./reports/:/reports/
  pa11y:
    image: repo.adeo.no:5443/soknad/soknad-docker-pa11y:1.0.0
    depends_on:
      - ci-test-server
    volumes:
      - ./pa11y/:/var/pa11y/
      - ./reports/:/reports/
    cap_add:
      - SYS_ADMIN
  chrome:
    container_name: chrome
    image: selenium/standalone-chrome:3.14.0
    ports:
      - 4444:4444
  testcafe:
    image: testcafe/testcafe
    command: 'firefox'
    depends_on:
      - ci-test-server
    volumes:
      - ./testcafe/:/tests